### ISSUE TITLE
This repository description is "Publicly apologies so others know you really mean it - A forum to submit and read public apologies https://mypublicapology.com"

### ISSUE THREAD

**Issue by Grumblesmith** [TheConnMan/my-public-apology#11]
"Publicly apologies" doesn't make any sense. It should either be 

> Public apologies so others know you really mean it

 or 

> Publicly apologize so others know you really mean it

**Comment by Grumblesmith** [comment]
Same mistake in the README

**Comment by TheConnMan** [comment]
:facepalm: Thanks for the find
